#!/bin/sh
# Common configuration include for openwrt-image-buildomatic
# This file is ALWAYS read before the device specific file
# so the device config file can use any of the variables here
#
# List of all OpenWRT packages: https://openwrt.org/packages/start

# Latest point release of each main release
RELEASE_18_06="18.06.9"
RELEASE_19_07="19.07.7"
RELEASE_21_02="21.02.0"

# Popular Luci apps
# This list is probably only valid for the 21.02 release
#   - luci-theme-material has intentionally been left out (it is rather ugly)
#   - luci-mod-rpc is for remote control, see https://openwrt.org/docs/techref/ubus
packages_luci_apps="
luci
luci-mod-rpc
luci-theme-openwrt-2020 luci-theme-bootstrap luci-theme-openwrt
luci-app-acme acme ca-certificates
luci-app-adblock adblock
luci-app-banip banip
luci-app-bcp38
luci-app-commands
luci-app-ddns
luci-app-fwknopd fwknopd
luci-app-https-dns-proxy https-dns-proxy
luci-app-sqm sqm-scripts sqm-scripts-extra
luci-app-statistics
  collectd collectd-mod-cpu collectd-mod-irq collectd-mod-thermal
  collectd-mod-network collectd-mod-sqm collectd-mod-iwinfo collectd-mod-ping
  collectd-mod-ethstat
  collectd-mod-processes collectd-mod-exec
luci-app-uhttpd
luci-app-vpn-policy-routing
luci-app-wireguard kmod-wireguard wireguard-tools qrencode
luci-app-wol
"

packages_unbound="luci-app-unbound unbound-checkconf unbound-anchor unbound-control-setup unbound-host"

packages_sec_dns="
luci-app-dnscrypt-proxy dnscrypt-proxy-resolvers
luci-app-https-dns-proxy
"

# luci-app-nlbwmon nlbwmon
# luci-app-dnscrypt-proxy

# All the most common USB Ethernet adapter kernel drivers
packages_usb_eth="
kmod-usb-core kmod-usb-net kmod-mii
kmod-usb-net-asix kmod-usb-net-asix-ax88179 kmod-usb-net-cdc-ether kmod-usb-net-ipheth
kmod-usb-net-kaweth kmod-usb-net-mcs7830 kmod-usb-net-pegasus kmod-usb-net-rtl8150
kmod-usb-net-rtl8152 kmod-usb-net-sr9700
"

# USB storage auto mounting
packages_usb_storage="
kmod-fs-exfat kmod-fs-ext4 kmod-fs-ntfs kmod-fuse kmod-usb-storage
kmod-usb2 kmod-usb2-pci kmod-usb3 kmod-fs-autofs4 kmod-usb-ohci kmod-usb-uhci
block-mount blockd e2fsprogs fdisk lsblk resize2fs losetup
"

# Total size of python-light plus python3-urllib is approximately 10MB
# 3.1M  /usr/lib/libpython3.9.so.1.0
# 6.6M	/usr/lib/python3.9/lib-dynload/*.so
packages_python="python3-light python3-urllib"

# List below taken from
# https://forum.openwrt.org/t/openwrt-arm64-quick-lxc-howto-guide-lms-in-debian-system-in-lxc-container/99835
packages_lxc="
xz tar gnupg \
kmod-ikconfig kmod-veth \
cgroupfs-mount cgroup-tools \
gnupg-utils gnupg2-dirmngr \
luci-app-lxc liblxc lxc lxc-attach lxc-auto lxc-autostart lxc-cgroup lxc-checkconfig \
lxc-common lxc-config lxc-configs lxc-console lxc-copy lxc-create lxc-destroy \
lxc-device lxc-execute lxc-freeze lxc-hooks lxc-info lxc-init lxc-ls lxc-monitor \
lxc-monitord lxc-snapshot lxc-start lxc-stop lxc-templates lxc-top lxc-unfreeze \
lxc-unprivileged lxc-unshare lxc-user-nic lxc-usernsexec lxc-wait rpcd-mod-lxc \
"
