#!/bin/sh
# TP-Link WDR3600 v1 configuration for openwrt-image-buildomatic

# Running OpenWRT image builder 18.06 on Ubuntu 20.04 requires at least:
#     sudo apt install python2 libncurses5-dev

#RELEASE=${RELEASE_18_06}
#RELEASE=${RELEASE_19_07}
RELEASE=${RELEASE_21_02}

if [ -z "${RELEASE}" ]; then echo "RELEASE is empty"; return 1; fi

# See targets here: https://downloads.openwrt.org/snapshots/targets
#
# device can be built with one of two TARGETs:
#   ar71xx/generic is usable for releases 17.01, 18.06, 19.07
#   ath79/generic  is usable for releases               19.07, 21.02
if echo "${RELEASE}" | grep -q "18.06"; then
    TARGET=ar71xx/generic
    PROFILE="tl-wdr3600-v1"
else
    TARGET=ath79/generic
    PROFILE="tplink_tl-wdr3600-v1"
fi

# See https://openwrt.org/packages/start
PACKAGES="luci htop"

FILES=""

DISABLED_SERVICES=""
